### ISSUE TITLE
Error on android or normal usage?

### ISSUE THREAD

**Issue by mannp** [avibrazil/digital-business-card#3]
Hi there, I am looking into using your digital card but only ever get the message get and rescan pass2u, even when pass2u is already installed.

It always takes me to the android store rather than opening the pass2u app when it is installed.

Shouldn't it open pass2u and import your card instead of only ever taking me to the store?

Thanks

**Comment by avibrazil** [comment]
You should scan it with Pass2U

Android has a weak support for passbook and user journey and experience is unpredictable. I’m sorry for that.
