### ISSUE TITLE
Feature request: Piwik as a replacement for google analytics

### ISSUE THREAD

**Issue by mannp** [avibrazil/digital-business-card#4]
Would be a great addition for the google free users :)

**Comment by avibrazil** [comment]
I'll add it if and when I have a need for that.
This is easy to add and I'll be happy to accept a pull request.

**Comment by mannp** [comment]
I've added the piwik tracking script to a copy of your code and it seems to work fine with the only change to your code was to remove the script block in index.html for google analytics.

Is there anything else I should remove to get rid of google analytics in full?

"ganalytics": "12345", is in data.json which I presume is your unique google identifier as a varable for use in the index.html script, so I could try adding a similar variable for a piwik instance.

Thanks in advance

**Comment by avibrazil** [comment]
Send me a pull request !
