### ISSUE TITLE
Current signing fee with your cert is <expensive>

### ISSUE THREAD

**Issue by mannp** [avibrazil/digital-business-card#5]
Wondered if you were still offering the ability to sign a card using your cert and what the current cost would be?

Thanks in advance :-)

**Comment by avibrazil** [comment]
I currently don't have an Apple developer ID to sign the wallet pass.
I only have SSL-certified servers to host it. And of course the bitcoin price skyrocketed in a way that I would change how much I would charge.

**Comment by thomasgarai** [comment]
Fantastic project!!! Save trees.. I love Brazil and all of its undertakings,no pun intended.
